const escapeHtml = (value = '') => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;');

export class AdminMapPanel extends HTMLElement {
  set handlers(value) { this._h = value; if (this.isConnected) this.load(); }
  connectedCallback() { this.render(); this.load(); }
  render() {
    this.innerHTML = `<section class="admin-panel admin-map-panel"><div class="tab-subbar"><h2>DANH SÁCH BẢN ĐỒ CHIẾN TRƯỜNG</h2><button type="button" class="button button--volt" data-toggle-form>+ THÊM BẢN ĐỒ MỚI</button></div><div data-table>Đang tải danh sách bản đồ...</div><form data-form hidden><h1 data-form-title>THÊM BẢN ĐỒ CHIẾN TRƯỜNG // MAP SECTOR</h1><div class="admin-grid-2"><div class="admin-form-group"><label>Mã ID Bản đồ</label><input name="id" required placeholder="summit"></div><div class="admin-form-group"><label>Tên bản đồ</label><input name="name" required placeholder="SUMMIT"></div></div><div class="admin-grid-2"><div class="admin-form-group"><label>Vị trí địa lý</label><input name="location"></div><div class="admin-form-group"><label>Tọa độ chiến lược</label><input name="coordinates"></div></div><div class="admin-form-group"><label>Giới thiệu bản đồ</label><textarea name="notes" rows="4"></textarea></div><div class="admin-form-group"><label>ALBUM ẢNH BẢN ĐỒ</label><div data-images></div><button type="button" class="button button--outline" data-add-image>+ THÊM ẢNH</button></div><button type="submit" class="admin-submit">LƯU BẢN ĐỒ VÀO HỆ THỐNG</button></form></section>`;
    this.querySelector('[data-toggle-form]').addEventListener('click', () => this.toggleForm());
    this.querySelector('[data-add-image]').addEventListener('click', () => this.addImage());
    this.querySelector('[data-form]').addEventListener('submit', (event) => this.submit(event));
    this.addImage();
  }
  async load() { if (!this._h?.onLoadMaps) return; try { this._maps = await this._h.onLoadMaps(); this.renderTable(); } catch (error) { this.querySelector('[data-table]').textContent = `Lỗi tải bản đồ: ${error.message}`; } }
  renderTable() { const table = this.querySelector('[data-table]'); table.innerHTML = `<table class="admin-table"><thead><tr><th>Ảnh</th><th>ID</th><th>Tên</th><th>Địa điểm</th><th>Xoay tua</th><th>Hành động</th></tr></thead><tbody>${(this._maps || []).map((map) => { const rotation = Boolean(map.isFeatured ?? map.is_featured); return `<tr><td><img src="${escapeHtml(map.imageUrl || map.image_url || '')}" width="60" height="34" alt=""></td><td><strong>${escapeHtml(map.id)}</strong></td><td>${escapeHtml(map.name)}</td><td>${escapeHtml(map.location || 'N/A')}</td><td><button type="button" class="btn-toggle ${rotation ? 'active' : 'inactive'}" data-toggle-map="${escapeHtml(map.id)}" data-current="${rotation}">${rotation ? '✔ ĐANG XOAY TUA' : '✖ KHÔNG XOAY TUA'}</button></td><td><div class="action-group"><button type="button" class="btn-action-edit" data-edit-map="${escapeHtml(map.id)}">SỬA</button><button type="button" class="btn-action-del" data-delete-map="${escapeHtml(map.id)}">XÓA</button></div></td></tr>`; }).join('') || '<tr><td colspan="6">Chưa có bản đồ nào.</td></tr>'}</tbody></table>`; table.querySelectorAll('[data-toggle-map]').forEach((button) => button.addEventListener('click', () => this.toggleRotation(button))); table.querySelectorAll('[data-edit-map]').forEach((button) => button.addEventListener('click', () => this.populate(this._maps.find((item) => String(item.id) === button.dataset.editMap)))); table.querySelectorAll('[data-delete-map]').forEach((button) => button.addEventListener('click', () => this.delete(button.dataset.deleteMap))); }
  async toggleRotation(button) { const next = button.dataset.current !== 'true'; button.disabled = true; try { await this._h.onToggleMapRotation(button.dataset.toggleMap, next); const target = this._maps.find((item) => String(item.id) === button.dataset.toggleMap); if (target) { target.isFeatured = next; target.is_featured = next; } this.renderTable(); } catch (error) { alert(error.message); button.disabled = false; } }
  async delete(id) { if (!confirm(`Bạn có chắc chắn muốn xóa bản đồ "${id}"?`)) return; try { await this._h.onDeleteMap(id); await this.load(); } catch (error) { alert(error.message); } }
  toggleForm() { const form = this.querySelector('[data-form]'); form.hidden = !form.hidden; this.querySelector('[data-toggle-form]').textContent = form.hidden ? '+ THÊM BẢN ĐỒ MỚI' : '✕ ĐÓNG FORM'; if (!form.hidden) this.reset(); }
  addImage(file = null) { const container = this.querySelector('[data-images]'); const row = document.createElement('div'); row.className = 'map-image-row'; row.innerHTML = `<span class="image-index">ẢNH #${container.children.length + 1}</span><input type="file" class="single-map-file" accept="image/*"><button type="button" class="btn-action-del" data-remove-image>XÓA</button>`; container.appendChild(row); if (file) row.querySelector('input')._existingUrl = file; row.querySelector('[data-remove-image]').addEventListener('click', () => { if (container.children.length > 1) row.remove(); this.renumberImages(); }); }
  renumberImages() { this.querySelectorAll('.map-image-row').forEach((row, index) => { row.querySelector('.image-index').textContent = `ẢNH #${index + 1}`; }); }
  populate(map) { if (!map) return; const form = this.querySelector('[data-form]'); form.hidden = false; this.querySelector('[data-toggle-form]').textContent = '✕ ĐÓNG FORM'; this._editingId = map.id; this._editingGallery = map.gallery || (map.imageUrl ? [map.imageUrl] : []); this.querySelector('[data-form-title]').textContent = `CHỈNH SỬA BẢN ĐỒ // ${map.name}`; ['id', 'name', 'location', 'coordinates', 'notes'].forEach((name) => { form.elements[name].value = map[name] || ''; }); form.elements.id.readOnly = true; form.querySelector('[data-images]').innerHTML = ''; this._editingGallery.forEach((url) => { const row = document.createElement('div'); row.className = 'map-image-row'; row.innerHTML = `<span class="image-index">ẢNH CŨ</span><a href="${escapeHtml(url)}" target="_blank">XEM ẢNH</a>`; form.querySelector('[data-images]').appendChild(row); }); this.addImage(); form.scrollIntoView({ behavior: 'smooth' }); }
  reset() { const form = this.querySelector('[data-form]'); form.reset(); form.elements.id.readOnly = false; this._editingId = null; this._editingGallery = []; form.querySelector('[data-images]').innerHTML = ''; this.addImage(); this.querySelector('[data-form-title]').textContent = 'THÊM BẢN ĐỒ CHIẾN TRƯỜNG // MAP SECTOR'; }
  async submit(event) { event.preventDefault(); const form = event.currentTarget; const button = form.querySelector('.admin-submit'); button.disabled = true; try { const urls = [...(this._editingGallery || [])]; for (const input of form.querySelectorAll('.single-map-file')) { const file = input.files[0]; if (file) { const url = await this._h.onUpload(file, 'agent-media'); if (url) urls.push(url); } } await this._h.onSaveMap({ id: form.elements.id.value.trim().toLowerCase(), name: form.elements.name.value.trim(), location: form.elements.location.value.trim(), coordinates: form.elements.coordinates.value.trim(), notes: form.elements.notes.value.trim(), image_url: urls[0] || '', is_featured: true, gallery: urls }); this.reset(); form.hidden = true; this.querySelector('[data-toggle-form]').textContent = '+ THÊM BẢN ĐỒ MỚI'; await this.load(); } catch (error) { alert(error.message); } finally { button.disabled = false; } }
}

customElements.define('admin-map-panel', AdminMapPanel);
